name: Build for Apple Platforms

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - '*'

env:
  PROJECT_SCHEME: MarkdownView  # Set your project's scheme here

jobs:
  build-ios:
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Xcode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: latest
          
      - name: Download iOS Simulator
        run: |
          xcrun simctl list > /dev/null # Required to prevent the next command from sometimes not working
          xcodebuild -downloadPlatform "iOS Simulator"

      - name: Build for iOS
        run: |
          xcodebuild clean build \
            -scheme ${{ env.PROJECT_SCHEME }} \
            -sdk iphonesimulator \
            -destination 'generic/platform=iOS Simulator' \
            -quiet

  build-macos:
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Xcode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: latest

      - name: Build for macOS
        run: |
          xcodebuild clean build \
            -scheme ${{ env.PROJECT_SCHEME }} \
            -sdk macosx \
            -destination 'platform=OS X' \
            -quiet

  build-tvos:
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Xcode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: latest
          
      - name: Download tvOS Simulator
        run: |
          xcrun simctl list > /dev/null # Required to prevent the next command from sometimes not working
          xcodebuild -downloadPlatform "tvOS Simulator"
          
      - name: Build for tvOS
        run: |
          xcodebuild clean build \
            -scheme ${{ env.PROJECT_SCHEME }} \
            -sdk appletvsimulator \
            -destination 'generic/platform=tvOS Simulator' \
            -quiet

  build-watchos:
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Xcode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: latest
          
      - name: Download watchOS Simulator
        run: |
          xcrun simctl list > /dev/null # Required to prevent the next command from sometimes not working
          xcodebuild -downloadPlatform "watchOS Simulator"

      - name: Build for watchOS
        run: |
          xcodebuild clean build \
            -scheme ${{ env.PROJECT_SCHEME }} \
            -sdk watchsimulator \
            -destination 'generic/platform=watchOS Simulator' \
            -quiet

  build-visionos:
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Xcode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: latest
          
      - name: Download visionOS Simulator
        run: |
          xcrun simctl list > /dev/null # Required to prevent the next command from sometimes not working
          xcodebuild -downloadPlatform "visionOS Simulator"

      - name: Build for visionOS
        run: |
          xcodebuild clean build \
            -scheme ${{ env.PROJECT_SCHEME }} \
            -sdk xros \
            -destination 'generic/platform=visionOS Simulator' \
            -quiet
